apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fundy.fullname" . }}-reports
  labels:
    {{- include "fundy.labels" . | nindent 4 }}
    {{- include "fundy.componentLabels" "reports" | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.reports }}
  selector:
    matchLabels:
      {{- include "fundy.selectorLabels" . | nindent 6 }}
      {{- include "fundy.componentLabels" "reports" | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fundy.selectorLabels" . | nindent 8 }}
        {{- include "fundy.componentLabels" "reports" | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: reports
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.images.reports.repository }}:{{ .Values.images.reports.tag }}"
        imagePullPolicy: {{ .Values.images.reports.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        envFrom:
        - secretRef:
             name: fundy-env-secrets
        env:
        - name: BUILDER_SERVICE_URL
          value: "http://{{ include "fundy.fullname" . }}-builder-svc:80"
        - name: ANALYTICS_SERVICE_URL
          value: "http://{{ include "fundy.fullname" . }}-analytics-svc:80"
        {{- if .Values.healthcheck.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthcheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthcheck.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthcheck.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthcheck.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources.reports | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
