{{- $root := . -}}
{{- $fullname := include "fundy.fullname" $root -}}
{{- $labels := include "fundy.labels" $root -}}
{{- $selectorLabels := include "fundy.selectorLabels" $root -}}
{{- $components := list "analytics" "jobs" "reports" "users" "frontend" "optimizer" "builder" "data" -}}

{{- range $component := $components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $component }}-svc
  labels:
    {{- $labels | nindent 4 }}
    {{- include "fundy.componentLabels" $component | nindent 4 }}
spec:
  type: {{ $root.Values.services.type }}
  ports:
    - port: {{ if eq $component "frontend" }}{{ $root.Values.services.ports.frontend }}{{ else }}{{ $root.Values.services.ports.backend }}{{ end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- $selectorLabels | nindent 4 }}
    {{- include "fundy.componentLabels" $component | nindent 4 }}
{{- end }}
