{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keda-waiting-page.serviceAccountName" . }}
  labels:
    {{- include "keda-waiting-page.labels" . | nindent 4 }}
{{- end }}
