apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-irc-server.fullname" . }}
  labels:
    {{- include "simple-irc-server.labels" . | nindent 4 }}
data:
  config.toml: |
{{ .Values.config.content | indent 4 }}
