apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-irc-server.fullname" . }}
  labels:
    {{- include "simple-irc-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: irc
      protocol: TCP
      name: irc
    {{- if .Values.service.enableSSL }}
    - port: {{ .Values.service.sslPort }}
      targetPort: ircs
      protocol: TCP
      name: ircs
    {{- end }}
  selector:
    {{- include "simple-irc-server.selectorLabels" . | nindent 4 }}
