apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-irc-server.fullname" . }}
  labels:
    {{- include "simple-irc-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: irc
      protocol: TCP
      name: irc
  selector:
    {{- include "simple-irc-server.selectorLabels" . | nindent 4 }}
