apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shannon.fullname" . }}-config
  labels:
    {{- include "shannon.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.shannon.config | nindent 4 }}
