apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shannon.fullname" . }}-config
  labels:
    {{- include "shannon.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- if typeIs "string" .Values.shannon.config }}
{{ .Values.shannon.config | indent 4 }}
{{- else }}
{{ .Values.shannon.config | toYaml | indent 4 }}
{{- end }}
