apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wh2pg.fullname" . }}-postgresql
  labels:
    {{- include "wh2pg.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secrets.postgresqlPassword | b64enc | quote }}
  {{- if .Values.secrets.webhookSecret }}
  webhook-secret: {{ .Values.secrets.webhookSecret | b64enc | quote }}
  {{- end }}
