apiVersion: v1
kind: ConfigMap
metadata:
  name: scale-config
  
data:
  LABEL_SELECTOR: "{{ .Values.config.labelSelector }}"
  BACKUP_PATH: "{{ .Values.config.backupPath }}"
  NAMESPACE: "{{ .Values.namespace }}"
  EXCLUDE_LIST: "{{ .Values.config.excludeList | join "," }}"
