apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerpipe.fullname" . }}-secret-env-vars
  labels:
    {{- include "powerpipe.labels" . | nindent 4 }}
stringData:

    {{- if .Values.powerpipe.secretEnvVars }}
    {{- toYaml .Values.powerpipe.secretEnvVars | nindent 2 }}
    {{- end }}
