apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "powerpipe.fullname" . }}
  labels:
    {{- include "powerpipe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.powerpipe.replicaCount }}
  selector:
    matchLabels:
      {{- include "powerpipe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.powerpipe.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "powerpipe.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.powerpipe.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.powerpipe.podSecurityContext | nindent 8 }}
      initContainers:
      {{- if .Values.powerpipe.modConfig }}
        - name: init-mod-config
          image: busybox:latest
          command: ['sh', '-c', 'cp /tmp/mod-config/mod.pp /home/powerpipe/mod.pp && chown 11234:11234 /home/powerpipe/mod.pp']
          volumeMounts:
            - name: mod-config
              mountPath: /tmp/mod-config
            - name: powerpipe-home
              mountPath: /home/powerpipe
      {{- end }}
      containers:
        - name: {{ include "powerpipe.fullname" . }}
          securityContext:
            {{- toYaml .Values.powerpipe.securityContext | nindent 12 }}
          image: "{{ .Values.powerpipe.image.repository }}:{{ .Values.powerpipe.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.powerpipe.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "powerpipe.fullname" . }}-cm-env-vars
          - secretRef:
              name: {{ include "powerpipe.fullname" . }}-secret-env-vars
          ports:
            - name: http
              containerPort: {{ .Values.powerpipe.containerPort }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - bash
              - ./healthcheck.sh
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          {{- if .Values.powerpipe.modConfig }}
            - name: powerpipe-home
              mountPath: /home/powerpipe
          {{- end }}
          {{- if .Values.powerpipe.resources }}
          resources:
            {{- toYaml .Values.powerpipe.resources | nindent 12 }}
          {{- else }}
          resources: {}
          {{- end }}
      {{- with .Values.powerpipe.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.powerpipe.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.powerpipe.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.powerpipe.modConfig }}
        - name: mod-config
          configMap:
            name: {{ include "powerpipe.fullname" . }}-mod-config
        - name: powerpipe-home
          emptyDir: {}
      {{- end }}
