{{- if .Values.secret.kubeConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kusanagi.fullname" . }}-kubeconfig
  labels:
    {{- include "kusanagi.labels" . | nindent 4 }}
type: Opaque
data:
  config: {{ .Values.secret.kubeConfig }}
{{- end }}
