{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kusanagi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusanagi.labels" . | nindent 4 }}
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kusanagi.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.monitoring.interval | default "30s" }}
    scrapeTimeout: {{ .Values.monitoring.scrapeTimeout | default "10s" }}
{{- end }}
