{{- if .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kusanagi.fullname" . }}-slack-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore | default "vault-backend" }}
    kind: ClusterSecretStore
  target:
    name: kusanagi-slack-credentials
    creationPolicy: Owner
  data:
  - secretKey: bot-token
    remoteRef:
      key: {{ .Values.vault.secrets.slack.path }}
      property: {{ .Values.vault.secrets.slack.botTokenKey }}
  - secretKey: channel-id
    remoteRef:
      key: {{ .Values.vault.secrets.slack.path }}
      property: {{ .Values.vault.secrets.slack.channelIdKey }}
{{- end }}
