apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent
  name: agent
  namespace: maker-management-platform
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - image: ghcr.io/maker-management-platform/agent:main
        imagePullPolicy: IfNotPresent
        name: agent
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /library
          name: library
        - mountPath: /data
          name: data
        - name: xpool
          mountPath: "/mnt/xpool"
          readOnly: false             
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: library-pvc
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      - name: xpool
        nfs:
          server: 192.168.0.50
          path: /xpool          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mmp-ui
  name: mmp-ui
  namespace: maker-management-platform
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mmp-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mmp-ui
    spec:
      containers:
      - env:
        - name: AGENT_ADDRESS
          value: agent:8000
        image: ghcr.io/maker-management-platform/mmp-ui:master
        imagePullPolicy: IfNotPresent
        name: mmp-ui
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent
  name: agent
  namespace: maker-management-platform
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: agent
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mmp-ui
  name: mmp-ui
  namespace: maker-management-platform
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: 8081
  selector:
    app: mmp-ui
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-dns
    freelens.app/resource-version: v1
    gethomepage.dev/description: maker-management-platform
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: https://maker-management-platform.p.zacharie.org/vite.svg
    gethomepage.dev/instance: public
    gethomepage.dev/name: maker-management-platform
    traefik.ingress.kubernetes.io/router.middlewares: default-traefik-auth@kubernetescrd
  name: maker-management-platform
  namespace: maker-management-platform
spec:
  ingressClassName: traefik
  rules:
  - host: maker-management-platform.p.zacharie.org
    http:
      paths:
      - backend:
          service:
            name: mmp-ui
            port:
              number: 8083
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - maker-management-platform.p.zacharie.org
    secretName: maker-management-platform.p.zacharie.org-tls
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: maker-management-platform
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client-jonas
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-pvc
  namespace: maker-management-platform
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-jonas
  volumeMode: Filesystem

# f6adad370103249544cb489aef23077c

# /mnt/xpool/share/share/3D

# fTV_rjQLUaOykrgBVqXAFGckLpstGIrDb4gL6slLd2c

# https://octoprint.zacharie.org