apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.agent.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.agent.persistence.data.size }}
  storageClassName: {{ .Values.agent.persistence.data.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.agent.persistence.library.accessMode }}
  resources:
    requests:
      storage: {{ .Values.agent.persistence.library.size }}
  storageClassName: {{ .Values.agent.persistence.library.storageClassName }}
  volumeMode: Filesystem
