apiVersion: v1
kind: Service
metadata:
  labels:
    app: mmp-ui
  name: mmp-ui
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: {{ .Values.ui.service.port }}
    protocol: TCP
    targetPort: {{ .Values.ui.service.targetPort }}
  selector:
    app: mmp-ui
  sessionAffinity: None
  type: ClusterIP
