apiVersion: v1
kind: Service
metadata:
  name: {{ include "proton-bridge.fullname" . }}
  labels:
    {{- include "proton-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.imapPort }}
      targetPort: imap
      protocol: TCP
      name: imap
    - port: {{ .Values.service.smtpPort }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "proton-bridge.selectorLabels" . | nindent 4 }}
