apiVersion: v2
name: kusanagi
description: Agent controller for K3s improvements
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - kusanagi
  - agent
  - rust
maintainers:
  - name: Joseph
