{{- if or .Values.global.ingress.traefik.enabled .Values.global.ingress.nginx.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "appflowy-gotrue.fullname" . }}-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /gotrue
{{- end }}
