apiVersion: v2
name: wh2pg-chart
description: Webhook to PostgreSQL - Service to receive webhooks and store them in PostgreSQL
type: application
version: 1.2.0
appVersion: "0.1.1"
keywords:
  - webhook
  - postgresql
  - rust
maintainers:
  - name: Joseph
home: https://github.com/JZacharie/wh2pg
sources:
  - https://github.com/JZacharie/wh2pg
