apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "maintenance.fullname" . }}-node-reader
  labels:
    {{- include "maintenance.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "maintenance.fullname" . }}-node-reader
  labels:
    {{- include "maintenance.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "maintenance.fullname" . }}-node-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "maintenance.fullname" .) }}
  namespace: {{ .Release.Namespace }}
