apiVersion: v2
name: stirling-pdf
description: Stirling-PDF Helm package
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
