{{- if .Values.gotrue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appflowy-sbx.fullname" . }}-gotrue
  labels:
    {{- include "appflowy-sbx.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotrue
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.0.199"
  ports:
    - port: 9999
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "appflowy-sbx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gotrue
{{- end }}
