{{- if .Values.proxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appflowy.fullname" . }}-proxy
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;

            # Web
            location / {
                proxy_pass http://{{ include "appflowy.fullname" . }}-web.{{ .Release.Namespace }}.svc:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # Cloud API
            location /api {
                proxy_pass http://{{ include "appflowy.fullname" . }}-cloud.{{ .Release.Namespace }}.svc:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # Cloud WebSocket
            location /ws {
                proxy_pass http://{{ include "appflowy.fullname" . }}-cloud.{{ .Release.Namespace }}.svc:8000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # GoTrue
            # Admin Console
            location /console {
                proxy_pass http://{{ include "appflowy.fullname" . }}-admin.{{ .Release.Namespace }}.svc:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /gotrue/ {
                rewrite ^/gotrue/(.*) /$1 break;
                proxy_pass http://{{ include "appflowy.fullname" . }}-gotrue.{{ .Release.Namespace }}.svc:9999;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
{{- end }}
